stages:
    - tslint
    - master-build

tslint:
    stage: tslint
    script:
        - tslint ./src/**/*.ts

master-build:
    stage: master-build
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG .
        - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG $CI_REGISTRY_IMAGE:latest
        - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
        - docker push $CI_REGISTRY_IMAGE:latest;
        - docker rmi -f $CI_REGISTRYкгт_IMAGE:$CI_COMMIT_TAG;
    only:
        - tags
