// import { IFilterField, filterFieldType } from '../../shared/filter/filter-fields.object';
// export const filterFields: IFilterField[] = [
// 	{
// 		activateClearButton: false,
// 		breadcrumbsChange: false,
// 		fieldType: filterFieldType.dropdown,
// 		formcontrolname: '[formcontrolname ="regionId"]',
// 		isHidden: false,
// 		inputData: 'Краснодар',
// 		name: 'Город',
// 		seoTextChange: false,
// 		tags: '23',
// 	},
// 	{
// 		activateClearButton: false,
// 		breadcrumbsChange: false,
// 		fieldType: filterFieldType.dropdown,
// 		formcontrolname: '[formcontrolname ="yearFrom"]',
// 		isHidden: false,
// 		inputData: '2012',
// 		name: 'Год от',
// 		seoTextChange: false,
// 		tags: 'yearFrom=2012',
// 	},
// 	{
// 		activateClearButton: false,
// 		breadcrumbsChange: false,
// 		fieldType: filterFieldType.dropdown,
// 		formcontrolname: '[formcontrolname ="yearTo"]',
// 		isHidden: false,
// 		inputData: '2017',
// 		name: 'до',
// 		seoTextChange: false,
// 		tags: 'yearTo=2017',
// 	},
// 	{
// 		activateClearButton: false,
// 		breadcrumbsChange: false,
// 		fieldType: filterFieldType.inputDropdown,
// 		formcontrolname: '[formcontrolname="make"]',
// 		isHidden: false,
// 		inputData: 'Au',
// 		name: 'Все марки',
// 		outputData: 'Audi',
// 		seoTextChange: false,
// 		tags: '10',
// 	},
// 	{
// 		activateClearButton: false,
// 		breadcrumbsChange: false,
// 		fieldType: filterFieldType.inputDropdown,
// 		formcontrolname: '[formcontrolname="model"]',
// 		isHidden: false,
// 		inputData: '1',
// 		name: 'Все модели',
// 		outputData: 'A1',
// 		seoTextChange: false,
// 		tags: '80',
// 	},
// ];
